# Generated by Django 6.0.4 on 2026-05-07 13:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название объема')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Объем',
                'verbose_name_plural': 'Объемы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CafePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('cafe_name', models.CharField(max_length=200, verbose_name='Название кафе')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hero_booking_button_text', models.CharField(default='Забронировать стол', max_length=50, verbose_name='Текст кнопки бронирования')),
                ('hero_menu_button_text', models.CharField(default='Наше меню', max_length=50, verbose_name='Текст кнопки меню')),
                ('show_menu_section', models.BooleanField(default=True, verbose_name='Показывать секцию меню')),
                ('menu_title', models.CharField(default='Наше меню', max_length=200, verbose_name='Заголовок секции меню (на странице)')),
                ('menu_nav_title', models.CharField(default='Меню', help_text='Как этот раздел будет называться в меню сайта', max_length=200, verbose_name='Название в навигации сайта')),
                ('menu_gallery', wagtail.fields.StreamField([('menu_gallery', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок, который отображается на странице', 'label': 'Заголовок блока', 'required': False}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cafe.MenuCategory',), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Категории для отображения'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('categories', 2)]], {})}, verbose_name='Галерея меню')),
                ('show_gallery_section', models.BooleanField(default=True, verbose_name='Показывать секцию галереи')),
                ('gallery_title', models.CharField(default='Фотогалерея', max_length=200, verbose_name='Заголовок секции галереи (на странице)')),
                ('gallery_nav_title', models.CharField(default='Галерея', help_text='Как этот раздел будет называться в меню сайта', max_length=200, verbose_name='Название в навигации сайта')),
                ('gallery_carousel', wagtail.fields.StreamField([('gallery_slide', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок на странице', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('description', 2)]], {})}, verbose_name='Слайды галереи')),
                ('show_booking_section', models.BooleanField(default=True, verbose_name='Показывать секцию бронирования')),
                ('booking_title', models.CharField(default='Забронировать стол', max_length=200, verbose_name='Заголовок секции бронирования (на странице)')),
                ('booking_nav_title', models.CharField(default='Бронь', help_text='Как этот раздел будет называться в меню сайта', max_length=200, verbose_name='Название в навигации сайта')),
                ('booking_intro', wagtail.fields.RichTextField(blank=True, verbose_name='Текст перед формой')),
                ('booking_form', wagtail.fields.StreamField([('booking_form', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок на странице', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Имя', 'label': 'Подпись поля Имя'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Введите ваше имя', 'label': 'Placeholder'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Телефон', 'label': 'Подпись поля Телефон'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '+7 (999) 123-45-67', 'label': 'Placeholder'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Дата', 'label': 'Подпись поля Дата'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Время', 'label': 'Подпись поля Время'}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Количество персон', 'label': 'Подпись поля'}), 8: ('wagtail.blocks.CharBlock', (), {'default': '2', 'label': 'Placeholder'}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Пожелания', 'label': 'Подпись поля Пожелания'}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Особые пожелания...', 'label': 'Placeholder'}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('name_label', 1), ('name_placeholder', 2), ('phone_label', 3), ('phone_placeholder', 4), ('date_label', 5), ('time_label', 6), ('persons_label', 7), ('persons_placeholder', 8), ('wishes_label', 9), ('wishes_placeholder', 10)]], {})}, verbose_name='Настройки формы')),
                ('booking_button_text', models.CharField(default='Забронировать', max_length=50, verbose_name='Текст кнопки')),
                ('booking_success_message', wagtail.fields.RichTextField(blank=True, default='<p>Спасибо! Мы свяжемся с вами для подтверждения брони.</p>', verbose_name='Сообщение после отправки')),
                ('show_contacts_section', models.BooleanField(default=False, verbose_name='Показывать секцию контактов')),
                ('contacts_title', models.CharField(default='Контакты', max_length=200, verbose_name='Заголовок секции контактов (на странице)')),
                ('contacts_nav_title', models.CharField(default='Контакты', help_text='Как этот раздел будет называться в меню сайта', max_length=200, verbose_name='Название в навигации сайта')),
                ('contacts', wagtail.fields.StreamField([('contact_block', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок на странице', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 1)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('contact_info', 2)]], {'label': 'Левая колонка'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Вставьте iframe код карты (Яндекс.Карты или Google Maps)', 'label': 'Код карты', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('map_code', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('map', 6)]], {'label': 'Правая колонка (карта)', 'max_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('left_content', 3), ('right_content', 7)]], {})}, verbose_name='Блок контактов')),
                ('from_address', models.EmailField(blank=True, default='noreply@cafe.com', max_length=255, verbose_name='Email отправителя')),
                ('to_address', models.EmailField(blank=True, max_length=255, verbose_name='Email получателя')),
                ('email_subject', models.CharField(blank=True, default='Новая заявка на бронирование', max_length=255, verbose_name='Тема письма')),
                ('booking_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение для секции бронирования')),
                ('contacts_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение для секции контактов')),
                ('gallery_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение для секции галереи')),
                ('hero_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение')),
                ('menu_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение для секции меню')),
            ],
            options={
                'verbose_name': 'Страница кафе',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.menucategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cafe.menuitem', verbose_name='Товар')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cafe.volumeoption', verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['-id'],
                'unique_together': {('item', 'volume')},
            },
        ),
    ]
